// Generated by CoffeeScript 1.7.1
(function() {
  var exports;

  exports = module.exports = function(user) {
    var json;
    user = user || {
      name: {},
      isAnon: true
    };
    json = {
      name: user.name,
      isAdmin: user.canAccessKeystone != null,
      content: user.content,
      isAnon: user.isAnon,
      _id: user._id
    };
    return json;
  };

}).call(this);
